substitutions:
  esphome_name: ${esphome_name}

esphome:
  <<: !include common/esphome.yaml
  
esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Optional manual IP
  manual_ip:
    static_ip: ${wifi_ip}
    gateway: 192.168.0.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${esphome_name} Fallback Hotspot"
    password: !secret hotspot_password

captive_portal:

sensor:
  <<: !include_dir_list common/sensor/
