substitutions:
  esphome_name: ${esphome_name}
  wifi_ip: ${wifi_ip}
  pcf8591_adc0: MQ-2
  pcf8591_adc1: MQ-4
  pcf8591_adc2: MQ-6
  pcf8591_adc3: -unused-

packages:
  common: !include common/base_sensor.yaml
  ad: !include pcf8591/pcf8591.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: D5
      inverted: true
      mode:
        input: true
        pullup: false
    name: "MQ-2 Alarm ${esphome_name}"
    device_class: gas
    filters:
      - delayed_on_off: 1s
  
  - platform: gpio
    pin:
      number: D6
      inverted: true
      mode:
        input: true
        pullup: false
    name: "MQ-4 Alarm ${esphome_name}"
    device_class: gas
    filters:
      - delayed_on_off: 1s
  
  - platform: gpio
    pin:
      number: D7
      inverted: true
      mode:
        input: true
        pullup: false
    name: "MQ-6 Alarm ${esphome_name}"
    device_class: gas
    filters:
      - delayed_on_off: 1s
