substitutions:
  esphome_name: autopilot
  wifi_ip: 192.168.0.26

packages:
  common: !include common/base_sensor.yaml

output:

  - platform: esp8266_pwm
    pin: D2
    frequency: 1000 Hz
    id: pwm_output

switch:

  - platform: gpio
    pin:
      number: D6
      inverted: true
    id: autopilot_switch_left
    name: "Autopilot left"
  
  - platform: gpio
    pin:
      number: D5
      inverted: true
    id: autopilot_switch_right
    name: "Autopilot right"

mqtt:
  on_json_message:
    - topic: device/autopilot/steer_left
      then:
        - lambda: |-
            float duration = x["duration"].as<float>();
            id(autopilot_switch_left).turn_on();
            delay(duration * 1000);
            id(autopilot_switch_left).turn_off();

    - topic: device/autopilot/steer_right
      then:
        - lambda: |-
            float duration = x["duration"].as<float>();
            id(autopilot_switch_right).turn_on();
            delay(duration * 1000);
            id(autopilot_switch_right).turn_off();