substitutions:
  esphome_name: unit_gamma
  wifi_ip: 192.168.0.13

packages:
  common: !include common/base_sensor.yaml

sensor:
  - platform: rotary_encoder
    id: anchor_chain_counter
    name: "Anchor chain counter"
    publish_initial_value: true
    pin_a:
      number: D3
      inverted: true
      mode:
        input: true
        pullup: true
    pin_b:
      number: D4
      inverted: true
      mode:
        input: true
        pullup: true

  - platform: template
    name: "Anchor chain length"
    id: anchor_chain_length
    unit_of_measurement: m
    accuracy_decimals: 2
    lambda: |-
      return id(anchor_chain_counter).state * 0.43;
