esphome:
  name: ${esphome_name}
  
esp8266:
  board: d1_mini
  restore_from_flash: true

# We use static IP
mdns:
  disabled: true

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Optional manual IP
  manual_ip:
    static_ip: ${wifi_ip}
    gateway: 192.168.0.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${esphome_name} Fallback Hotspot"
    password: !secret hotspot_password

mqtt:
  broker: 192.168.0.4
  topic_prefix: device/${esphome_name}
  log_topic: 

captive_portal:

sensor: !include_dir_list sensor/
